package com.yubo.wechat.content.dao;

import com.yubo.wechat.content.dao.pojo.MessageText;

public interface MessageTextMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_text
     *
     * @mbggenerated Mon May 16 19:53:42 PDT 2016
     */
    int deleteByPrimaryKey(Integer messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_text
     *
     * @mbggenerated Mon May 16 19:53:42 PDT 2016
     */
    int insert(MessageText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_text
     *
     * @mbggenerated Mon May 16 19:53:42 PDT 2016
     */
    int insertSelective(MessageText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_text
     *
     * @mbggenerated Mon May 16 19:53:42 PDT 2016
     */
    MessageText selectByPrimaryKey(Integer messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_text
     *
     * @mbggenerated Mon May 16 19:53:42 PDT 2016
     */
    int updateByPrimaryKeySelective(MessageText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_text
     *
     * @mbggenerated Mon May 16 19:53:42 PDT 2016
     */
    int updateByPrimaryKey(MessageText record);
}