package com.yubo.wechat.user.dao.pojo;

import java.util.Date;

public class ArgUserProgress {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column arg_user_progress.arg_user_progress_id
	 * @mbggenerated  Fri Aug 05 17:14:18 CST 2016
	 */
	private Integer argUserProgressId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column arg_user_progress.arg_topic_id
	 * @mbggenerated  Fri Aug 05 17:14:18 CST 2016
	 */
	private Integer argTopicId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column arg_user_progress.arg_step
	 * @mbggenerated  Fri Aug 05 17:14:18 CST 2016
	 */
	private Integer argStep;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column arg_user_progress.last_modify
	 * @mbggenerated  Fri Aug 05 17:14:18 CST 2016
	 */
	private Date lastModify;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column arg_user_progress.user_id
	 * @mbggenerated  Fri Aug 05 17:14:18 CST 2016
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column arg_user_progress.user_identification_id
	 * @mbggenerated  Fri Aug 05 17:14:18 CST 2016
	 */
	private Integer userIdentificationId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column arg_user_progress.arg_user_progress_id
	 * @return  the value of arg_user_progress.arg_user_progress_id
	 * @mbggenerated  Fri Aug 05 17:14:18 CST 2016
	 */
	public Integer getArgUserProgressId() {
		return argUserProgressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column arg_user_progress.arg_user_progress_id
	 * @param argUserProgressId  the value for arg_user_progress.arg_user_progress_id
	 * @mbggenerated  Fri Aug 05 17:14:18 CST 2016
	 */
	public void setArgUserProgressId(Integer argUserProgressId) {
		this.argUserProgressId = argUserProgressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column arg_user_progress.arg_topic_id
	 * @return  the value of arg_user_progress.arg_topic_id
	 * @mbggenerated  Fri Aug 05 17:14:18 CST 2016
	 */
	public Integer getArgTopicId() {
		return argTopicId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column arg_user_progress.arg_topic_id
	 * @param argTopicId  the value for arg_user_progress.arg_topic_id
	 * @mbggenerated  Fri Aug 05 17:14:18 CST 2016
	 */
	public void setArgTopicId(Integer argTopicId) {
		this.argTopicId = argTopicId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column arg_user_progress.arg_step
	 * @return  the value of arg_user_progress.arg_step
	 * @mbggenerated  Fri Aug 05 17:14:18 CST 2016
	 */
	public Integer getArgStep() {
		return argStep;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column arg_user_progress.arg_step
	 * @param argStep  the value for arg_user_progress.arg_step
	 * @mbggenerated  Fri Aug 05 17:14:18 CST 2016
	 */
	public void setArgStep(Integer argStep) {
		this.argStep = argStep;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column arg_user_progress.last_modify
	 * @return  the value of arg_user_progress.last_modify
	 * @mbggenerated  Fri Aug 05 17:14:18 CST 2016
	 */
	public Date getLastModify() {
		return lastModify;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column arg_user_progress.last_modify
	 * @param lastModify  the value for arg_user_progress.last_modify
	 * @mbggenerated  Fri Aug 05 17:14:18 CST 2016
	 */
	public void setLastModify(Date lastModify) {
		this.lastModify = lastModify;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column arg_user_progress.user_id
	 * @return  the value of arg_user_progress.user_id
	 * @mbggenerated  Fri Aug 05 17:14:18 CST 2016
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column arg_user_progress.user_id
	 * @param userId  the value for arg_user_progress.user_id
	 * @mbggenerated  Fri Aug 05 17:14:18 CST 2016
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column arg_user_progress.user_identification_id
	 * @return  the value of arg_user_progress.user_identification_id
	 * @mbggenerated  Fri Aug 05 17:14:18 CST 2016
	 */
	public Integer getUserIdentificationId() {
		return userIdentificationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column arg_user_progress.user_identification_id
	 * @param userIdentificationId  the value for arg_user_progress.user_identification_id
	 * @mbggenerated  Fri Aug 05 17:14:18 CST 2016
	 */
	public void setUserIdentificationId(Integer userIdentificationId) {
		this.userIdentificationId = userIdentificationId;
	}
}