package com.yubo.wechat.user.dao.pojo;

import java.util.Date;

public class FeederBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feeder_base.keeper_id
     *
     * @mbggenerated Tue Jun 07 17:09:36 CST 2016
     */
    private Integer keeperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feeder_base.keeper_account
     *
     * @mbggenerated Tue Jun 07 17:09:36 CST 2016
     */
    private String keeperAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feeder_base.wechat_id
     *
     * @mbggenerated Tue Jun 07 17:09:36 CST 2016
     */
    private String wechatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feeder_base.school_id
     *
     * @mbggenerated Tue Jun 07 17:09:36 CST 2016
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feeder_base.create_time
     *
     * @mbggenerated Tue Jun 07 17:09:36 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feeder_base.last_login_time
     *
     * @mbggenerated Tue Jun 07 17:09:36 CST 2016
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feeder_base.valid
     *
     * @mbggenerated Tue Jun 07 17:09:36 CST 2016
     */
    private Byte valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feeder_base.keeper_id
     *
     * @return the value of feeder_base.keeper_id
     *
     * @mbggenerated Tue Jun 07 17:09:36 CST 2016
     */
    public Integer getKeeperId() {
        return keeperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feeder_base.keeper_id
     *
     * @param keeperId the value for feeder_base.keeper_id
     *
     * @mbggenerated Tue Jun 07 17:09:36 CST 2016
     */
    public void setKeeperId(Integer keeperId) {
        this.keeperId = keeperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feeder_base.keeper_account
     *
     * @return the value of feeder_base.keeper_account
     *
     * @mbggenerated Tue Jun 07 17:09:36 CST 2016
     */
    public String getKeeperAccount() {
        return keeperAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feeder_base.keeper_account
     *
     * @param keeperAccount the value for feeder_base.keeper_account
     *
     * @mbggenerated Tue Jun 07 17:09:36 CST 2016
     */
    public void setKeeperAccount(String keeperAccount) {
        this.keeperAccount = keeperAccount == null ? null : keeperAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feeder_base.wechat_id
     *
     * @return the value of feeder_base.wechat_id
     *
     * @mbggenerated Tue Jun 07 17:09:36 CST 2016
     */
    public String getWechatId() {
        return wechatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feeder_base.wechat_id
     *
     * @param wechatId the value for feeder_base.wechat_id
     *
     * @mbggenerated Tue Jun 07 17:09:36 CST 2016
     */
    public void setWechatId(String wechatId) {
        this.wechatId = wechatId == null ? null : wechatId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feeder_base.school_id
     *
     * @return the value of feeder_base.school_id
     *
     * @mbggenerated Tue Jun 07 17:09:36 CST 2016
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feeder_base.school_id
     *
     * @param schoolId the value for feeder_base.school_id
     *
     * @mbggenerated Tue Jun 07 17:09:36 CST 2016
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feeder_base.create_time
     *
     * @return the value of feeder_base.create_time
     *
     * @mbggenerated Tue Jun 07 17:09:36 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feeder_base.create_time
     *
     * @param createTime the value for feeder_base.create_time
     *
     * @mbggenerated Tue Jun 07 17:09:36 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feeder_base.last_login_time
     *
     * @return the value of feeder_base.last_login_time
     *
     * @mbggenerated Tue Jun 07 17:09:36 CST 2016
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feeder_base.last_login_time
     *
     * @param lastLoginTime the value for feeder_base.last_login_time
     *
     * @mbggenerated Tue Jun 07 17:09:36 CST 2016
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feeder_base.valid
     *
     * @return the value of feeder_base.valid
     *
     * @mbggenerated Tue Jun 07 17:09:36 CST 2016
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feeder_base.valid
     *
     * @param valid the value for feeder_base.valid
     *
     * @mbggenerated Tue Jun 07 17:09:36 CST 2016
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }
}