package com.yubo.wechat.user.dao.pojo;

import java.util.Date;

public class SchoolBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_base.school_id
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_base.school_name
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    private String schoolName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_base.valid
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    private Boolean valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_base.last_modify
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    private Date lastModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_base.school_id
     *
     * @return the value of school_base.school_id
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_base.school_id
     *
     * @param schoolId the value for school_base.school_id
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_base.school_name
     *
     * @return the value of school_base.school_name
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_base.school_name
     *
     * @param schoolName the value for school_base.school_name
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName == null ? null : schoolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_base.valid
     *
     * @return the value of school_base.valid
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_base.valid
     *
     * @param valid the value for school_base.valid
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_base.last_modify
     *
     * @return the value of school_base.last_modify
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    public Date getLastModify() {
        return lastModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_base.last_modify
     *
     * @param lastModify the value for school_base.last_modify
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    public void setLastModify(Date lastModify) {
        this.lastModify = lastModify;
    }
}