package com.yubo.wechat.user.dao.pojo;

import java.util.Date;

public class TalkHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_history.talk_id
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    private Long talkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_history.user_id
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_history.pet_id
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    private Integer petId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_history.last_talk_func_code
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    private Integer lastTalkFuncCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_history.last_talk_user_said
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    private String lastTalkUserSaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_history.last_talk_time
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    private Date lastTalkTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_history.valid
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    private Boolean valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_history.last_talk_pet_said
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    private byte[] lastTalkPetSaid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_history.talk_id
     *
     * @return the value of talk_history.talk_id
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    public Long getTalkId() {
        return talkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_history.talk_id
     *
     * @param talkId the value for talk_history.talk_id
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    public void setTalkId(Long talkId) {
        this.talkId = talkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_history.user_id
     *
     * @return the value of talk_history.user_id
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_history.user_id
     *
     * @param userId the value for talk_history.user_id
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_history.pet_id
     *
     * @return the value of talk_history.pet_id
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    public Integer getPetId() {
        return petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_history.pet_id
     *
     * @param petId the value for talk_history.pet_id
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    public void setPetId(Integer petId) {
        this.petId = petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_history.last_talk_func_code
     *
     * @return the value of talk_history.last_talk_func_code
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    public Integer getLastTalkFuncCode() {
        return lastTalkFuncCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_history.last_talk_func_code
     *
     * @param lastTalkFuncCode the value for talk_history.last_talk_func_code
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    public void setLastTalkFuncCode(Integer lastTalkFuncCode) {
        this.lastTalkFuncCode = lastTalkFuncCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_history.last_talk_user_said
     *
     * @return the value of talk_history.last_talk_user_said
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    public String getLastTalkUserSaid() {
        return lastTalkUserSaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_history.last_talk_user_said
     *
     * @param lastTalkUserSaid the value for talk_history.last_talk_user_said
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    public void setLastTalkUserSaid(String lastTalkUserSaid) {
        this.lastTalkUserSaid = lastTalkUserSaid == null ? null : lastTalkUserSaid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_history.last_talk_time
     *
     * @return the value of talk_history.last_talk_time
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    public Date getLastTalkTime() {
        return lastTalkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_history.last_talk_time
     *
     * @param lastTalkTime the value for talk_history.last_talk_time
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    public void setLastTalkTime(Date lastTalkTime) {
        this.lastTalkTime = lastTalkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_history.valid
     *
     * @return the value of talk_history.valid
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_history.valid
     *
     * @param valid the value for talk_history.valid
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_history.last_talk_pet_said
     *
     * @return the value of talk_history.last_talk_pet_said
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    public byte[] getLastTalkPetSaid() {
        return lastTalkPetSaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_history.last_talk_pet_said
     *
     * @param lastTalkPetSaid the value for talk_history.last_talk_pet_said
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    public void setLastTalkPetSaid(byte[] lastTalkPetSaid) {
        this.lastTalkPetSaid = lastTalkPetSaid;
    }
}