package com.yubo.wechat.user.dao.pojo;

import java.util.Date;

public class UserIdentification {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_identification.identi_id
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	private Integer identiId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_identification.student_name
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	private String studentName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_identification.student_class
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	private String studentClass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_identification.student_no
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	private String studentNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_identification.student_sex
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	private Short studentSex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_identification.school_id
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	private Integer schoolId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_identification.identi_code
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	private String identiCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_identification.valid
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	private Boolean valid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_identification.last_modify
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	private Date lastModify;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_identification.identi_id
	 * @return  the value of user_identification.identi_id
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	public Integer getIdentiId() {
		return identiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_identification.identi_id
	 * @param identiId  the value for user_identification.identi_id
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	public void setIdentiId(Integer identiId) {
		this.identiId = identiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_identification.student_name
	 * @return  the value of user_identification.student_name
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	public String getStudentName() {
		return studentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_identification.student_name
	 * @param studentName  the value for user_identification.student_name
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	public void setStudentName(String studentName) {
		this.studentName = studentName == null ? null : studentName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_identification.student_class
	 * @return  the value of user_identification.student_class
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	public String getStudentClass() {
		return studentClass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_identification.student_class
	 * @param studentClass  the value for user_identification.student_class
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	public void setStudentClass(String studentClass) {
		this.studentClass = studentClass == null ? null : studentClass.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_identification.student_no
	 * @return  the value of user_identification.student_no
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	public String getStudentNo() {
		return studentNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_identification.student_no
	 * @param studentNo  the value for user_identification.student_no
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	public void setStudentNo(String studentNo) {
		this.studentNo = studentNo == null ? null : studentNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_identification.student_sex
	 * @return  the value of user_identification.student_sex
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	public Short getStudentSex() {
		return studentSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_identification.student_sex
	 * @param studentSex  the value for user_identification.student_sex
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	public void setStudentSex(Short studentSex) {
		this.studentSex = studentSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_identification.school_id
	 * @return  the value of user_identification.school_id
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	public Integer getSchoolId() {
		return schoolId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_identification.school_id
	 * @param schoolId  the value for user_identification.school_id
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	public void setSchoolId(Integer schoolId) {
		this.schoolId = schoolId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_identification.identi_code
	 * @return  the value of user_identification.identi_code
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	public String getIdentiCode() {
		return identiCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_identification.identi_code
	 * @param identiCode  the value for user_identification.identi_code
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	public void setIdentiCode(String identiCode) {
		this.identiCode = identiCode == null ? null : identiCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_identification.valid
	 * @return  the value of user_identification.valid
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	public Boolean getValid() {
		return valid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_identification.valid
	 * @param valid  the value for user_identification.valid
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	public void setValid(Boolean valid) {
		this.valid = valid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_identification.last_modify
	 * @return  the value of user_identification.last_modify
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	public Date getLastModify() {
		return lastModify;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_identification.last_modify
	 * @param lastModify  the value for user_identification.last_modify
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	public void setLastModify(Date lastModify) {
		this.lastModify = lastModify;
	}
}