package com.yubo.wechat.user.dao;

import java.util.List;
import java.util.Map;

import com.yubo.wechat.user.dao.pojo.ArgQuestion;

public interface ArgQuestionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table arg_question
	 * @mbggenerated  Sun Aug 07 09:02:57 CST 2016
	 */
	int deleteByPrimaryKey(Integer argQuestionId);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table arg_question
	 * @mbggenerated  Sun Aug 07 09:02:57 CST 2016
	 */
	int insert(ArgQuestion record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table arg_question
	 * @mbggenerated  Sun Aug 07 09:02:57 CST 2016
	 */
	int insertSelective(ArgQuestion record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table arg_question
	 * @mbggenerated  Sun Aug 07 09:02:57 CST 2016
	 */
	ArgQuestion selectByPrimaryKey(Integer argQuestionId);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table arg_question
	 * @mbggenerated  Sun Aug 07 09:02:57 CST 2016
	 */
	int updateByPrimaryKeySelective(ArgQuestion record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table arg_question
	 * @mbggenerated  Sun Aug 07 09:02:57 CST 2016
	 */
	int updateByPrimaryKey(ArgQuestion record);


	/**
	 * 
	 * @param record
	 * @return
	 */
	int countByParam(ArgQuestion record);
	
	
	/**
	 * 
	 * @param param
	 * @return
	 */
	List<ArgQuestion> selectByParam(Map<String,Object> param);
}