package com.yubo.wechat.user.dao;

import java.util.List;

import com.yubo.wechat.user.dao.pojo.ArgUserProgress;

public interface ArgUserProgressMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table arg_user_progress
	 * @mbggenerated  Sun Aug 07 09:02:57 CST 2016
	 */
	int deleteByPrimaryKey(Integer argUserProgressId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table arg_user_progress
	 * @mbggenerated  Sun Aug 07 09:02:57 CST 2016
	 */
	int insert(ArgUserProgress record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table arg_user_progress
	 * @mbggenerated  Sun Aug 07 09:02:57 CST 2016
	 */
	int insertSelective(ArgUserProgress record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table arg_user_progress
	 * @mbggenerated  Sun Aug 07 09:02:57 CST 2016
	 */
	ArgUserProgress selectByPrimaryKey(Integer argUserProgressId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table arg_user_progress
	 * @mbggenerated  Sun Aug 07 09:02:57 CST 2016
	 */
	int updateByPrimaryKeySelective(ArgUserProgress record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table arg_user_progress
	 * @mbggenerated  Sun Aug 07 09:02:57 CST 2016
	 */
	int updateByPrimaryKey(ArgUserProgress record);

	/**
	 * 
	 * @param record
	 * @return
	 */
	List<ArgUserProgress> selectByParam(ArgUserProgress record);
}