package com.yubo.wechat.user.dao;

import java.util.List;

import com.yubo.wechat.user.dao.pojo.TalkHistory;

public interface TalkHistoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table talk_history
	 * @mbggenerated  Tue May 31 14:25:10 CST 2016
	 */
	int deleteByPrimaryKey(Long talkId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table talk_history
	 * @mbggenerated  Tue May 31 14:25:10 CST 2016
	 */
	int insert(TalkHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table talk_history
	 * @mbggenerated  Tue May 31 14:25:10 CST 2016
	 */
	int insertSelective(TalkHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table talk_history
	 * @mbggenerated  Tue May 31 14:25:10 CST 2016
	 */
	TalkHistory selectByPrimaryKey(Long talkId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table talk_history
	 * @mbggenerated  Tue May 31 14:25:10 CST 2016
	 */
	int updateByPrimaryKeySelective(TalkHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table talk_history
	 * @mbggenerated  Tue May 31 14:25:10 CST 2016
	 */
	int updateByPrimaryKey(TalkHistory record);

	/**
	 * 根据要求查询
	 * @param param
	 * @return
	 */
	List<TalkHistory> selectBySelective(TalkHistory param);
}