package com.yubo.wechat.user.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.yubo.wechat.user.dao.pojo.UserBase;

@Repository
public interface UserBaseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Wed May 18 22:39:44 CST 2016
	 */
	int deleteByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Wed May 18 22:39:44 CST 2016
	 */
	int insert(UserBase record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Wed May 18 22:39:44 CST 2016
	 */
	int insertSelective(UserBase record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Wed May 18 22:39:44 CST 2016
	 */
	UserBase selectByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Wed May 18 22:39:44 CST 2016
	 */
	int updateByPrimaryKeySelective(UserBase record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Wed May 18 22:39:44 CST 2016
	 */
	int updateByPrimaryKey(UserBase record);

	/**
	 * 根据条件进行查询
	 * @param param
	 * @return
	 */
	List<UserBase> selectByParam(UserBase param);
}