package com.yubo.wechat.user.dao;

import com.yubo.wechat.user.dao.pojo.UserPetFavor;

public interface UserPetFavorMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_pet_favor
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	int deleteByPrimaryKey(Integer favorId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_pet_favor
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	int insert(UserPetFavor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_pet_favor
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	int insertSelective(UserPetFavor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_pet_favor
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	UserPetFavor selectByPrimaryKey(Integer favorId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_pet_favor
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	int updateByPrimaryKeySelective(UserPetFavor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_pet_favor
	 * @mbggenerated  Tue May 17 08:27:43 PDT 2016
	 */
	int updateByPrimaryKey(UserPetFavor record);
}