package com.yubo.wechat.user.dao;

import com.yubo.wechat.user.dao.pojo.UserIdentification;

public interface UserIdentificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_identification
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    int deleteByPrimaryKey(Integer identiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_identification
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    int insert(UserIdentification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_identification
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    int insertSelective(UserIdentification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_identification
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    UserIdentification selectByPrimaryKey(Integer identiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_identification
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    int updateByPrimaryKeySelective(UserIdentification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_identification
     *
     * @mbggenerated Tue May 17 06:26:02 PDT 2016
     */
    int updateByPrimaryKey(UserIdentification record);
}