package com.yubo.wechat.pet.dao.pojo;

import java.util.Date;

public class PetBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_base.pet_id
     *
     * @mbggenerated Tue May 17 06:26:41 PDT 2016
     */
    private Integer petId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_base.pet_name
     *
     * @mbggenerated Tue May 17 06:26:41 PDT 2016
     */
    private String petName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_base.pet_level
     *
     * @mbggenerated Tue May 17 06:26:41 PDT 2016
     */
    private Double petLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_base.school_id
     *
     * @mbggenerated Tue May 17 06:26:41 PDT 2016
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_base.valid
     *
     * @mbggenerated Tue May 17 06:26:41 PDT 2016
     */
    private Boolean valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_base.last_modify
     *
     * @mbggenerated Tue May 17 06:26:41 PDT 2016
     */
    private Date lastModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_base.pet_id
     *
     * @return the value of pet_base.pet_id
     *
     * @mbggenerated Tue May 17 06:26:41 PDT 2016
     */
    public Integer getPetId() {
        return petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_base.pet_id
     *
     * @param petId the value for pet_base.pet_id
     *
     * @mbggenerated Tue May 17 06:26:41 PDT 2016
     */
    public void setPetId(Integer petId) {
        this.petId = petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_base.pet_name
     *
     * @return the value of pet_base.pet_name
     *
     * @mbggenerated Tue May 17 06:26:41 PDT 2016
     */
    public String getPetName() {
        return petName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_base.pet_name
     *
     * @param petName the value for pet_base.pet_name
     *
     * @mbggenerated Tue May 17 06:26:41 PDT 2016
     */
    public void setPetName(String petName) {
        this.petName = petName == null ? null : petName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_base.pet_level
     *
     * @return the value of pet_base.pet_level
     *
     * @mbggenerated Tue May 17 06:26:41 PDT 2016
     */
    public Double getPetLevel() {
        return petLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_base.pet_level
     *
     * @param petLevel the value for pet_base.pet_level
     *
     * @mbggenerated Tue May 17 06:26:41 PDT 2016
     */
    public void setPetLevel(Double petLevel) {
        this.petLevel = petLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_base.school_id
     *
     * @return the value of pet_base.school_id
     *
     * @mbggenerated Tue May 17 06:26:41 PDT 2016
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_base.school_id
     *
     * @param schoolId the value for pet_base.school_id
     *
     * @mbggenerated Tue May 17 06:26:41 PDT 2016
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_base.valid
     *
     * @return the value of pet_base.valid
     *
     * @mbggenerated Tue May 17 06:26:41 PDT 2016
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_base.valid
     *
     * @param valid the value for pet_base.valid
     *
     * @mbggenerated Tue May 17 06:26:41 PDT 2016
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_base.last_modify
     *
     * @return the value of pet_base.last_modify
     *
     * @mbggenerated Tue May 17 06:26:41 PDT 2016
     */
    public Date getLastModify() {
        return lastModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_base.last_modify
     *
     * @param lastModify the value for pet_base.last_modify
     *
     * @mbggenerated Tue May 17 06:26:41 PDT 2016
     */
    public void setLastModify(Date lastModify) {
        this.lastModify = lastModify;
    }
}