package com.yubo.wechat.content.dao;

import com.yubo.wechat.content.dao.pojo.PetBase;

public interface PetBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_base
     *
     * @mbggenerated Mon May 16 19:51:38 PDT 2016
     */
    int deleteByPrimaryKey(Integer petId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_base
     *
     * @mbggenerated Mon May 16 19:51:38 PDT 2016
     */
    int insert(PetBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_base
     *
     * @mbggenerated Mon May 16 19:51:38 PDT 2016
     */
    int insertSelective(PetBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_base
     *
     * @mbggenerated Mon May 16 19:51:38 PDT 2016
     */
    PetBase selectByPrimaryKey(Integer petId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_base
     *
     * @mbggenerated Mon May 16 19:51:38 PDT 2016
     */
    int updateByPrimaryKeySelective(PetBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_base
     *
     * @mbggenerated Mon May 16 19:51:38 PDT 2016
     */
    int updateByPrimaryKey(PetBase record);
}