package com.yubo.wechat.vote.dao;

import java.util.List;
import java.util.Map;

import com.yubo.wechat.vote.dao.pojo.UserVoteRecord;

public interface UserVoteRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_vote_record
     *
     * @mbggenerated Fri May 20 11:04:13 CST 2016
     */
    int deleteByPrimaryKey(Long uvoteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_vote_record
     *
     * @mbggenerated Fri May 20 11:04:13 CST 2016
     */
    int insert(UserVoteRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_vote_record
     *
     * @mbggenerated Fri May 20 11:04:13 CST 2016
     */
    int insertSelective(UserVoteRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_vote_record
     *
     * @mbggenerated Fri May 20 11:04:13 CST 2016
     */
    UserVoteRecord selectByPrimaryKey(Long uvoteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_vote_record
     *
     * @mbggenerated Fri May 20 11:04:13 CST 2016
     */
    int updateByPrimaryKeySelective(UserVoteRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_vote_record
     *
     * @mbggenerated Fri May 20 11:04:13 CST 2016
     */
    int updateByPrimaryKey(UserVoteRecord record);
    
    
	int countByParam(UserVoteRecord record);
	
	List<UserVoteRecord> selectByParam(Map<String,Object> param);
	
	/**
	 * 投票统计
	 * @param voteId 需要统计的投票ID
	 * @return
	 */
	List<Map<String,Object>> countVoteResult(long voteId);
}