package com.yubo.wechat.content.dao.pojo;

public class MessageText {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_text.message_id
     *
     * @mbggenerated Mon May 16 19:53:42 PDT 2016
     */
    private Integer messageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_text.perid_id
     *
     * @mbggenerated Mon May 16 19:53:42 PDT 2016
     */
    private Integer peridId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_text.content
     *
     * @mbggenerated Mon May 16 19:53:42 PDT 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_text.valid
     *
     * @mbggenerated Mon May 16 19:53:42 PDT 2016
     */
    private Boolean valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_text.message_id
     *
     * @return the value of message_text.message_id
     *
     * @mbggenerated Mon May 16 19:53:42 PDT 2016
     */
    public Integer getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_text.message_id
     *
     * @param messageId the value for message_text.message_id
     *
     * @mbggenerated Mon May 16 19:53:42 PDT 2016
     */
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_text.perid_id
     *
     * @return the value of message_text.perid_id
     *
     * @mbggenerated Mon May 16 19:53:42 PDT 2016
     */
    public Integer getPeridId() {
        return peridId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_text.perid_id
     *
     * @param peridId the value for message_text.perid_id
     *
     * @mbggenerated Mon May 16 19:53:42 PDT 2016
     */
    public void setPeridId(Integer peridId) {
        this.peridId = peridId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_text.content
     *
     * @return the value of message_text.content
     *
     * @mbggenerated Mon May 16 19:53:42 PDT 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_text.content
     *
     * @param content the value for message_text.content
     *
     * @mbggenerated Mon May 16 19:53:42 PDT 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_text.valid
     *
     * @return the value of message_text.valid
     *
     * @mbggenerated Mon May 16 19:53:42 PDT 2016
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_text.valid
     *
     * @param valid the value for message_text.valid
     *
     * @mbggenerated Mon May 16 19:53:42 PDT 2016
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }
}