package com.yubo.wechat.content.dao.pojo;

public class MessageText {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column message_text.message_id
	 * @mbggenerated  Tue May 31 11:14:24 CST 2016
	 */
	private Integer messageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column message_text.period_id
	 * @mbggenerated  Tue May 31 11:14:24 CST 2016
	 */
	private Integer periodId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column message_text.content
	 * @mbggenerated  Tue May 31 11:14:24 CST 2016
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column message_text.valid
	 * @mbggenerated  Tue May 31 11:14:24 CST 2016
	 */
	private Boolean valid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column message_text.func_code
	 * @mbggenerated  Tue May 31 11:14:24 CST 2016
	 */
	private Integer funcCode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message_text.message_id
	 * @return  the value of message_text.message_id
	 * @mbggenerated  Tue May 31 11:14:24 CST 2016
	 */
	public Integer getMessageId() {
		return messageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message_text.message_id
	 * @param messageId  the value for message_text.message_id
	 * @mbggenerated  Tue May 31 11:14:24 CST 2016
	 */
	public void setMessageId(Integer messageId) {
		this.messageId = messageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message_text.period_id
	 * @return  the value of message_text.period_id
	 * @mbggenerated  Tue May 31 11:14:24 CST 2016
	 */
	public Integer getPeriodId() {
		return periodId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message_text.period_id
	 * @param periodId  the value for message_text.period_id
	 * @mbggenerated  Tue May 31 11:14:24 CST 2016
	 */
	public void setPeriodId(Integer periodId) {
		this.periodId = periodId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message_text.content
	 * @return  the value of message_text.content
	 * @mbggenerated  Tue May 31 11:14:24 CST 2016
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message_text.content
	 * @param content  the value for message_text.content
	 * @mbggenerated  Tue May 31 11:14:24 CST 2016
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message_text.valid
	 * @return  the value of message_text.valid
	 * @mbggenerated  Tue May 31 11:14:24 CST 2016
	 */
	public Boolean getValid() {
		return valid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message_text.valid
	 * @param valid  the value for message_text.valid
	 * @mbggenerated  Tue May 31 11:14:24 CST 2016
	 */
	public void setValid(Boolean valid) {
		this.valid = valid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column message_text.func_code
	 * @return  the value of message_text.func_code
	 * @mbggenerated  Tue May 31 11:14:24 CST 2016
	 */
	public Integer getFuncCode() {
		return funcCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column message_text.func_code
	 * @param funcCode  the value for message_text.func_code
	 * @mbggenerated  Tue May 31 11:14:24 CST 2016
	 */
	public void setFuncCode(Integer funcCode) {
		this.funcCode = funcCode;
	}
}