package com.yubo.wechat.content.dao;

import com.yubo.wechat.content.dao.pojo.SchoolBase;

public interface SchoolBaseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table school_base
	 * @mbggenerated  Mon May 16 19:50:36 PDT 2016
	 */
	int deleteByPrimaryKey(Integer schoolId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table school_base
	 * @mbggenerated  Mon May 16 19:50:36 PDT 2016
	 */
	int insert(SchoolBase record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table school_base
	 * @mbggenerated  Mon May 16 19:50:36 PDT 2016
	 */
	int insertSelective(SchoolBase record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table school_base
	 * @mbggenerated  Mon May 16 19:50:36 PDT 2016
	 */
	SchoolBase selectByPrimaryKey(Integer schoolId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table school_base
	 * @mbggenerated  Mon May 16 19:50:36 PDT 2016
	 */
	int updateByPrimaryKeySelective(SchoolBase record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table school_base
	 * @mbggenerated  Mon May 16 19:50:36 PDT 2016
	 */
	int updateByPrimaryKey(SchoolBase record);
}