package com.yubo.wechat.content.dao;

import org.springframework.stereotype.Repository;

import com.yubo.wechat.content.dao.pojo.UserBase;

@Repository
public interface UserBaseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Mon May 16 19:50:36 PDT 2016
	 */
	int deleteByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Mon May 16 19:50:36 PDT 2016
	 */
	int insert(UserBase record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Mon May 16 19:50:36 PDT 2016
	 */
	int insertSelective(UserBase record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Mon May 16 19:50:36 PDT 2016
	 */
	UserBase selectByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Mon May 16 19:50:36 PDT 2016
	 */
	int updateByPrimaryKeySelective(UserBase record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_base
	 * @mbggenerated  Mon May 16 19:50:36 PDT 2016
	 */
	int updateByPrimaryKey(UserBase record);
}