package com.yubo.wechat.content.dao;

import com.yubo.wechat.content.dao.pojo.UserPetFavor;

public interface UserPetFavorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pet_favor
     *
     * @mbggenerated Mon May 16 19:50:36 PDT 2016
     */
    int deleteByPrimaryKey(Integer favorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pet_favor
     *
     * @mbggenerated Mon May 16 19:50:36 PDT 2016
     */
    int insert(UserPetFavor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pet_favor
     *
     * @mbggenerated Mon May 16 19:50:36 PDT 2016
     */
    int insertSelective(UserPetFavor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pet_favor
     *
     * @mbggenerated Mon May 16 19:50:36 PDT 2016
     */
    UserPetFavor selectByPrimaryKey(Integer favorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pet_favor
     *
     * @mbggenerated Mon May 16 19:50:36 PDT 2016
     */
    int updateByPrimaryKeySelective(UserPetFavor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pet_favor
     *
     * @mbggenerated Mon May 16 19:50:36 PDT 2016
     */
    int updateByPrimaryKey(UserPetFavor record);
}