package com.yubo.feeder.dao.pojo;

import java.util.Date;

public class VoteBase {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vote_base.vote_id
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	private Long voteId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vote_base.title
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vote_base.answers
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	private String answers;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vote_base.type
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	private Short type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vote_base.question
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	private String question;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vote_base.start_time
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	private Date startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vote_base.end_time
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	private Date endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vote_base.valid
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	private Byte valid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vote_base.summary
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	private String summary;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vote_base.feed_back_pic_url
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	private String feedBackPicUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vote_base.look_config
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	private String lookConfig;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vote_base.vote_id
	 * @return  the value of vote_base.vote_id
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	public Long getVoteId() {
		return voteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vote_base.vote_id
	 * @param voteId  the value for vote_base.vote_id
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	public void setVoteId(Long voteId) {
		this.voteId = voteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vote_base.title
	 * @return  the value of vote_base.title
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vote_base.title
	 * @param title  the value for vote_base.title
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vote_base.answers
	 * @return  the value of vote_base.answers
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	public String getAnswers() {
		return answers;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vote_base.answers
	 * @param answers  the value for vote_base.answers
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	public void setAnswers(String answers) {
		this.answers = answers == null ? null : answers.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vote_base.type
	 * @return  the value of vote_base.type
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	public Short getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vote_base.type
	 * @param type  the value for vote_base.type
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	public void setType(Short type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vote_base.question
	 * @return  the value of vote_base.question
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	public String getQuestion() {
		return question;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vote_base.question
	 * @param question  the value for vote_base.question
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	public void setQuestion(String question) {
		this.question = question == null ? null : question.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vote_base.start_time
	 * @return  the value of vote_base.start_time
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vote_base.start_time
	 * @param startTime  the value for vote_base.start_time
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vote_base.end_time
	 * @return  the value of vote_base.end_time
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vote_base.end_time
	 * @param endTime  the value for vote_base.end_time
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vote_base.valid
	 * @return  the value of vote_base.valid
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	public Byte getValid() {
		return valid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vote_base.valid
	 * @param valid  the value for vote_base.valid
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	public void setValid(Byte valid) {
		this.valid = valid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vote_base.summary
	 * @return  the value of vote_base.summary
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	public String getSummary() {
		return summary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vote_base.summary
	 * @param summary  the value for vote_base.summary
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	public void setSummary(String summary) {
		this.summary = summary == null ? null : summary.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vote_base.feed_back_pic_url
	 * @return  the value of vote_base.feed_back_pic_url
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	public String getFeedBackPicUrl() {
		return feedBackPicUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vote_base.feed_back_pic_url
	 * @param feedBackPicUrl  the value for vote_base.feed_back_pic_url
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	public void setFeedBackPicUrl(String feedBackPicUrl) {
		this.feedBackPicUrl = feedBackPicUrl == null ? null : feedBackPicUrl
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vote_base.look_config
	 * @return  the value of vote_base.look_config
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	public String getLookConfig() {
		return lookConfig;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vote_base.look_config
	 * @param lookConfig  the value for vote_base.look_config
	 * @mbggenerated  Tue May 24 22:54:20 CST 2016
	 */
	public void setLookConfig(String lookConfig) {
		this.lookConfig = lookConfig == null ? null : lookConfig.trim();
	}
}