package com.yubo.wechat.vote.dao.pojo;

import java.util.Date;

public class UserVoteRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_vote_record.uvote_id
     *
     * @mbggenerated Fri May 20 11:04:13 CST 2016
     */
    private Long uvoteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_vote_record.user_id
     *
     * @mbggenerated Fri May 20 11:04:13 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_vote_record.vote_id
     *
     * @mbggenerated Fri May 20 11:04:13 CST 2016
     */
    private Long voteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_vote_record.user_choice_answer
     *
     * @mbggenerated Fri May 20 11:04:13 CST 2016
     */
    private String userChoiceAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_vote_record.user_open_answer
     *
     * @mbggenerated Fri May 20 11:04:13 CST 2016
     */
    private String userOpenAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_vote_record.answer_time
     *
     * @mbggenerated Fri May 20 11:04:13 CST 2016
     */
    private Date answerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_vote_record.last_modify
     *
     * @mbggenerated Fri May 20 11:04:13 CST 2016
     */
    private Date lastModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_vote_record.visiable
     *
     * @mbggenerated Fri May 20 11:04:13 CST 2016
     */
    private Byte visiable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_vote_record.uvote_id
     *
     * @return the value of user_vote_record.uvote_id
     *
     * @mbggenerated Fri May 20 11:04:13 CST 2016
     */
    public Long getUvoteId() {
        return uvoteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_vote_record.uvote_id
     *
     * @param uvoteId the value for user_vote_record.uvote_id
     *
     * @mbggenerated Fri May 20 11:04:13 CST 2016
     */
    public void setUvoteId(Long uvoteId) {
        this.uvoteId = uvoteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_vote_record.user_id
     *
     * @return the value of user_vote_record.user_id
     *
     * @mbggenerated Fri May 20 11:04:13 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_vote_record.user_id
     *
     * @param userId the value for user_vote_record.user_id
     *
     * @mbggenerated Fri May 20 11:04:13 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_vote_record.vote_id
     *
     * @return the value of user_vote_record.vote_id
     *
     * @mbggenerated Fri May 20 11:04:13 CST 2016
     */
    public Long getVoteId() {
        return voteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_vote_record.vote_id
     *
     * @param voteId the value for user_vote_record.vote_id
     *
     * @mbggenerated Fri May 20 11:04:13 CST 2016
     */
    public void setVoteId(Long voteId) {
        this.voteId = voteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_vote_record.user_choice_answer
     *
     * @return the value of user_vote_record.user_choice_answer
     *
     * @mbggenerated Fri May 20 11:04:13 CST 2016
     */
    public String getUserChoiceAnswer() {
        return userChoiceAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_vote_record.user_choice_answer
     *
     * @param userChoiceAnswer the value for user_vote_record.user_choice_answer
     *
     * @mbggenerated Fri May 20 11:04:13 CST 2016
     */
    public void setUserChoiceAnswer(String userChoiceAnswer) {
        this.userChoiceAnswer = userChoiceAnswer == null ? null : userChoiceAnswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_vote_record.user_open_answer
     *
     * @return the value of user_vote_record.user_open_answer
     *
     * @mbggenerated Fri May 20 11:04:13 CST 2016
     */
    public String getUserOpenAnswer() {
        return userOpenAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_vote_record.user_open_answer
     *
     * @param userOpenAnswer the value for user_vote_record.user_open_answer
     *
     * @mbggenerated Fri May 20 11:04:13 CST 2016
     */
    public void setUserOpenAnswer(String userOpenAnswer) {
        this.userOpenAnswer = userOpenAnswer == null ? null : userOpenAnswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_vote_record.answer_time
     *
     * @return the value of user_vote_record.answer_time
     *
     * @mbggenerated Fri May 20 11:04:13 CST 2016
     */
    public Date getAnswerTime() {
        return answerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_vote_record.answer_time
     *
     * @param answerTime the value for user_vote_record.answer_time
     *
     * @mbggenerated Fri May 20 11:04:13 CST 2016
     */
    public void setAnswerTime(Date answerTime) {
        this.answerTime = answerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_vote_record.last_modify
     *
     * @return the value of user_vote_record.last_modify
     *
     * @mbggenerated Fri May 20 11:04:13 CST 2016
     */
    public Date getLastModify() {
        return lastModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_vote_record.last_modify
     *
     * @param lastModify the value for user_vote_record.last_modify
     *
     * @mbggenerated Fri May 20 11:04:13 CST 2016
     */
    public void setLastModify(Date lastModify) {
        this.lastModify = lastModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_vote_record.visiable
     *
     * @return the value of user_vote_record.visiable
     *
     * @mbggenerated Fri May 20 11:04:13 CST 2016
     */
    public Byte getVisiable() {
        return visiable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_vote_record.visiable
     *
     * @param visiable the value for user_vote_record.visiable
     *
     * @mbggenerated Fri May 20 11:04:13 CST 2016
     */
    public void setVisiable(Byte visiable) {
        this.visiable = visiable;
    }
}